### ISSUE TITLE
Delays causing states to not sum to 1

### ISSUE THREAD

**Issue by bobverity** [cran/odin#1]
Hey,

I've just been playing around with a simple SEIR model where hosts are in E for a fixed interval. I think I can achieve this through the following delay equations:
```
## Core equations for transitions between compartments:
deriv(S) <- - beta * S * I / N
deriv(E) <- beta * S * I / N - beta * S_lag * I_lag / N      # this is just for tracking hosts in latent stage
deriv(I) <- beta * S_lag * I_lag / N - gamma * I
deriv(R) <- gamma * I

S_lag <- delay(S, mean_delay)
I_lag <- delay(I, mean_delay)

## Initial states:
initial(S) <- N - I_init
initial(E) <- 0
initial(I) <- I_init
initial(R) <- 0

## User defined parameters - default in parentheses:
N <- user(1e3)
I_init <- user(1)
beta <- user(0.3)
gamma <- user(0.05)
mean_delay <- user(10)
```
I run this model with this code:
```
library(tidyverse)
library(odin)

odin_generator <- odin("data/odin_delay.R")

odin_model <- odin_generator$new()

odin_output <- odin_model$run(t = 0:300)

tail(odin_output)

# dynamics look about right, but E dips below zero
odin_output |>
  as.data.frame() |>
  pivot_longer(cols = -t, names_to = "state") |>
  ggplot() + theme_bw() +
  geom_line(aes(x = t, y = value, col = state))
```
But I'm finding that when I look at the `tail` of the output, the E state drops below zero. The total sum over all states is still 1e3, as I would expect. Am I doing something wrong here? Is it something to do with how I'm specifying delays?

Thanks for any help!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
